version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Esteban1102
      MYSQL_DATABASE: ambiefacBd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  spring-app:
    image: estsban1102/backendappambiefac-spring-app:1.0.3
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data: