version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 2001
      MYSQL_DATABASE: ambiefacBd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_network

  spring-app:
    image: bladimirvargas/backend-ambiefacapp-pdn:1.0.1
    container_name: spring-container
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql-data: